// Copyright 2026 AxonOps Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// character_cross_validation_test.go asserts agreement between the
// project's character-tier surfaces (LevenshteinDistance,
// DamerauLevenshteinFullDistance, JaroScore, JaroWinklerScore) and the
// jellyfish==1.2.1 reference corpus committed at
// testdata/cross-validation/character/vectors.json. The corpus carries
// four scores per entry — levenshtein_distance,
// damerau_levenshtein_distance, jaro_similarity, jaro_winkler_similarity
// — emitted by scripts/gen-character-cross-validation.py with the
// jellyfish version pinned to JELLYFISH_VERSION = "1.2.1".
//
// Tolerance:
//   - Integer surfaces (LevenshteinDistance, DamerauLevenshteinFullDistance):
//     EXACT equality. Off-by-one would indicate a wave-front or DP-table
//     bug.
//   - Float surfaces (JaroScore, JaroWinklerScore): |our_score -
//     jellyfish_score| <= 1e-9 (matches the Phase 3 SWG / Phase 4
//     Ratcliff-Obershelp / Phase 6 token-ratio epsilon conventions).
//
// Surface mapping caveats (documented divergences):
//   - jellyfish 1.2.1's damerau_levenshtein_distance ships the
//     UNRESTRICTED (Lowrance-Wagner 1975, "true") Damerau-Levenshtein
//     variant, NOT the OSA / restricted variant. The corpus therefore
//     cross-validates against fuzzymatch.DamerauLevenshteinFullDistance.
//     The OSA surface (DamerauLevenshteinOSADistance) is covered by
//     primary-source reference vectors in damerau_osa_test.go and is
//     NOT part of this corpus.
//   - jellyfish.jaro_similarity("", "") returns 0.0; fuzzymatch.JaroScore
//     ("", "") returns 1.0 by catalogue convention. Corpus entries
//     affected by this divergence carry variant_divergence=true and
//     divergent_jellyfish_jaro / divergent_jellyfish_jw fields; the
//     Go-side assertion checks the FUZZYMATCH-expected value (which is
//     what the corpus's jaro_similarity / jaro_winkler_similarity fields
//     contain) NOT the raw jellyfish value.
//
// The corpus is regenerated by `make regen-character-cross-validation`
// (developer-only — requires `pip install jellyfish==1.2.1`). CI does NOT
// require Python at test time; the committed JSON is the verification
// fixture read directly by Go.
//
// Failure messages include the jellyfish_version, python_version, and
// surface field name for triage — same pattern as
// token_ratio_cross_validation_test.go::TestTokenRatios_CrossValidation.

package fuzzymatch_test

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/axonops/fuzzymatch"
)

// characterCrossValidationEpsilon is the float-comparison tolerance for
// the Jaro / JaroWinkler entries. Integer surfaces (Levenshtein,
// Damerau full distances) use EXACT equality — see the per-surface
// check below.
const characterCrossValidationEpsilon = 1e-9

// characterEntry is one entry in the committed
// testdata/cross-validation/character/vectors.json corpus produced by
// scripts/gen-character-cross-validation.py. The two distance fields are
// plain int (jellyfish returns integers); the two similarity fields are
// float64. The variant_divergence + divergent_jellyfish_* fields document
// known fuzzymatch-vs-jellyfish divergences (see file header).
type characterEntry struct {
	Name                       string  `json:"name"`
	A                          string  `json:"a"`
	B                          string  `json:"b"`
	LevenshteinDistance        int     `json:"levenshtein_distance"`
	DamerauLevenshteinDistance int     `json:"damerau_levenshtein_distance"`
	JaroSimilarity             float64 `json:"jaro_similarity"`
	JaroWinklerSimilarity      float64 `json:"jaro_winkler_similarity"`
	// VariantDivergence is true when the entry's expected scores differ
	// from jellyfish's raw output. When true, jaro_similarity and
	// jaro_winkler_similarity carry the FUZZYMATCH-expected values, and
	// divergent_jellyfish_jaro / divergent_jellyfish_jw carry the raw
	// jellyfish values for reviewer triage.
	VariantDivergence      bool    `json:"variant_divergence,omitempty"`
	DivergentJellyfishJaro float64 `json:"divergent_jellyfish_jaro,omitempty"`
	DivergentJellyfishJW   float64 `json:"divergent_jellyfish_jw,omitempty"`
}

// characterMetadata is the top-level _metadata block — pins the
// generator's pinned jellyfish version, the Python version that produced
// the corpus, and the regeneration timestamp (informational only).
type characterMetadata struct {
	JellyfishVersion string `json:"jellyfish_version"`
	PythonVersion    string `json:"python_version"`
	RegeneratedAt    string `json:"regenerated_at"`
}

// characterCorpus is the top-level shape of the corpus JSON file — see
// scripts/gen-character-cross-validation.py for the generator schema.
type characterCorpus struct {
	Version  int               `json:"version"`
	Metadata characterMetadata `json:"_metadata"`
	Entries  []characterEntry  `json:"entries"`
}

// TestCharacter_CrossValidation asserts agreement between the project's
// LevenshteinDistance / DamerauLevenshteinFullDistance / JaroScore /
// JaroWinklerScore surfaces and jellyfish==1.2.1's reference outputs for
// the same algorithms.
//
// Surface mapping (corpus → fuzzymatch):
//
//	levenshtein_distance         → LevenshteinDistance(a, b)
//	damerau_levenshtein_distance → DamerauLevenshteinFullDistance(a, b)
//	jaro_similarity              → JaroScore(a, b)
//	jaro_winkler_similarity      → JaroWinklerScore(a, b)
//
// jellyfish 1.2.1's damerau_levenshtein_distance ships the UNRESTRICTED
// (Lowrance-Wagner 1975, "true") Damerau-Levenshtein variant, NOT the
// OSA variant — confirmed by direct probe against the pinned release.
// Therefore the corpus is cross-validated against
// DamerauLevenshteinFullDistance specifically; the OSA surface
// (DamerauLevenshteinOSADistance) is exercised by primary-source
// reference vectors in damerau_osa_test.go and is intentionally NOT part
// of this corpus.
func TestCharacter_CrossValidation(t *testing.T) {
	path := filepath.Join("testdata", "cross-validation", "character", "vectors.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("TestCharacter_CrossValidation: read %s: %v (regenerate with `make regen-character-cross-validation`)", path, err)
	}
	var c characterCorpus
	if err := json.Unmarshal(raw, &c); err != nil {
		t.Fatalf("TestCharacter_CrossValidation: parse %s: %v", path, err)
	}
	if c.Version != 1 {
		t.Fatalf("TestCharacter_CrossValidation: unsupported corpus version %d (want 1)", c.Version)
	}
	if len(c.Entries) == 0 {
		t.Fatalf("TestCharacter_CrossValidation: empty corpus")
	}
	if c.Metadata.JellyfishVersion == "" {
		t.Fatalf("TestCharacter_CrossValidation: corpus missing _metadata.jellyfish_version — regenerate with `make regen-character-cross-validation`")
	}
	if c.Metadata.PythonVersion == "" {
		t.Fatalf("TestCharacter_CrossValidation: corpus missing _metadata.python_version — regenerate with `make regen-character-cross-validation`")
	}
	// Mirror the Python-version gate in the generator: parse
	// python_version into (major, minor) and assert >= 3.7.
	parts := strings.SplitN(c.Metadata.PythonVersion, ".", 3)
	if len(parts) < 2 {
		t.Fatalf("TestCharacter_CrossValidation: malformed python_version %q (want major.minor[.patch])", c.Metadata.PythonVersion)
	}
	major, err1 := strconv.Atoi(parts[0])
	minor, err2 := strconv.Atoi(parts[1])
	if err1 != nil || err2 != nil {
		t.Fatalf("TestCharacter_CrossValidation: non-numeric python_version %q", c.Metadata.PythonVersion)
	}
	if major < 3 || (major == 3 && minor < 7) {
		t.Fatalf("TestCharacter_CrossValidation: corpus generated with Python %s; script minimum is 3.7 (required for dict insertion-order stability)", c.Metadata.PythonVersion)
	}

	for _, e := range c.Entries {
		e := e // local copy for the closure

		t.Run(e.Name+"/levenshtein_distance", func(t *testing.T) {
			got := fuzzymatch.LevenshteinDistance(e.A, e.B)
			if got != e.LevenshteinDistance {
				t.Errorf("LevenshteinDistance(%q, %q) = %d; jellyfish levenshtein_distance = %d (jellyfish %s, python %s)",
					e.A, e.B, got, e.LevenshteinDistance,
					c.Metadata.JellyfishVersion, c.Metadata.PythonVersion)
			}
		})

		t.Run(e.Name+"/damerau_full_distance", func(t *testing.T) {
			got := fuzzymatch.DamerauLevenshteinFullDistance(e.A, e.B)
			if got != e.DamerauLevenshteinDistance {
				t.Errorf("DamerauLevenshteinFullDistance(%q, %q) = %d; jellyfish damerau_levenshtein_distance (unrestricted/true Damerau) = %d (jellyfish %s, python %s)",
					e.A, e.B, got, e.DamerauLevenshteinDistance,
					c.Metadata.JellyfishVersion, c.Metadata.PythonVersion)
			}
		})

		t.Run(e.Name+"/jaro_similarity", func(t *testing.T) {
			got := fuzzymatch.JaroScore(e.A, e.B)
			delta := math.Abs(got - e.JaroSimilarity)
			if delta > characterCrossValidationEpsilon {
				t.Errorf("JaroScore(%q, %q) = %.17g; jellyfish jaro_similarity = %.17g (delta %.2e, tol %g, jellyfish %s, python %s)",
					e.A, e.B, got, e.JaroSimilarity, delta, characterCrossValidationEpsilon,
					c.Metadata.JellyfishVersion, c.Metadata.PythonVersion)
			}
		})

		t.Run(e.Name+"/jaro_winkler_similarity", func(t *testing.T) {
			got := fuzzymatch.JaroWinklerScore(e.A, e.B)
			delta := math.Abs(got - e.JaroWinklerSimilarity)
			if delta > characterCrossValidationEpsilon {
				t.Errorf("JaroWinklerScore(%q, %q) = %.17g; jellyfish jaro_winkler_similarity = %.17g (delta %.2e, tol %g, jellyfish %s, python %s)",
					e.A, e.B, got, e.JaroWinklerSimilarity, delta, characterCrossValidationEpsilon,
					c.Metadata.JellyfishVersion, c.Metadata.PythonVersion)
			}
		})
	}
}

// TestCharacter_CrossValidation_CorpusShape asserts the committed corpus
// contains at least 30 entries spanning the categories promised by plan
// 08.5-10 task 1:
//
//   - identity / empty / one-empty (≥ 3 — checked via "identity",
//     "both_empty", "one_empty")
//   - Levenshtein reference (≥ 1 — checked via "lev_" prefix)
//   - Damerau (full / unrestricted) transposition (≥ 1 — checked via
//     "dl_full_" prefix; jellyfish 1.2.1 ships the unrestricted variant)
//   - Jaro reference (≥ 1 — checked via "jaro_" prefix)
//   - JaroWinkler reference (≥ 1 — checked via "jw_" prefix)
//   - length-mismatched (≥ 1 — checked via "len_mismatch_" prefix)
//   - long ASCII (≥ 1 — checked via "long_ascii_" prefix)
//
// Together with TestCharacter_CrossValidation, this shape gate prevents
// a future regression where someone trims the corpus to remove a
// load-bearing fixture (which would silently disarm the relevant gate
// without surfacing a delta).
func TestCharacter_CrossValidation_CorpusShape(t *testing.T) {
	path := filepath.Join("testdata", "cross-validation", "character", "vectors.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	var c characterCorpus
	if err := json.Unmarshal(raw, &c); err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}

	if len(c.Entries) < 30 {
		t.Errorf("corpus has %d entries; want >= 30 (plan 08.5-10 task 1 success criterion)", len(c.Entries))
	}

	if c.Metadata.JellyfishVersion != "1.2.1" {
		t.Errorf("corpus _metadata.jellyfish_version = %q; want %q (the pinned version per plan 08.5-10)", c.Metadata.JellyfishVersion, "1.2.1")
	}

	categories := map[string]bool{
		"identity":        false,
		"both_empty":      false,
		"one_empty":       false,
		"lev_":            false,
		"dl_full_":        false,
		"jaro_":           false,
		"jw_":             false,
		"len_mismatch_":   false,
		"long_ascii_":     false,
		"fully_different": false,
	}
	for _, e := range c.Entries {
		for cat := range categories {
			if strings.Contains(e.Name, cat) {
				categories[cat] = true
			}
		}
	}
	for cat, found := range categories {
		if !found {
			t.Errorf("corpus is missing the %q category (no entry name contains the substring) — was a load-bearing fixture trimmed?", cat)
		}
	}
}
