# fuzzymatch — canonical Makefile.
#
# All 19 targets enumerated in CLAUDE.md "Makefile Targets". `make check` is
# the aggregate local pre-PR gate; CI mirrors it from .github/workflows/ci.yml.
# Targets that depend on artefacts produced by later plans (01-03 release
# pipeline, 01-04 determinism infra) are tolerant no-ops printing a "pending"
# message until those plans land.

SHELL := /usr/bin/env bash

GO          ?= go
GOFMT       ?= gofmt
GOIMPORTS   ?= goimports
GOLANGCILINT?= golangci-lint
GOVULNCHECK ?= govulncheck
BENCHSTAT   ?= benchstat
GORELEASER  ?= goreleaser

MODULE_PATH      := github.com/axonops/fuzzymatch
BDD_DIR          := tests/bdd
COVERAGE_FILE    := coverage.out
BENCH_FILE       := bench.txt
BENCH_NEW_FILE   := bench.txt.new
COVERAGE_FLOOR   := 95.0

.PHONY: check test test-bdd test-fuzz lint vet fmt fmt-check bench bench-compare \
	coverage coverage-check tidy tidy-check security verify-deps-allowlist \
	verify-determinism verify-license-headers regen-swg-cross-validation \
	regen-ratcliff-obershelp-cross-validation regen-token-ratio-cross-validation \
	regen-phonetic-cross-validation regen-character-cross-validation \
	regen-qgram-cross-validation regen-monge-elkan-cross-validation \
	release-check clean

# `check` — the canonical pre-PR aggregate gate. CI runs the same target.
check: fmt-check vet lint verify-license-headers verify-deps-allowlist tidy-check security test coverage coverage-check
	@echo "OK: make check passed."

# ---- test targets ---------------------------------------------------------

test:
	$(GO) test -race -shuffle=on -count=1 ./...

test-bdd:
	cd $(BDD_DIR) && $(GO) test -race -count=1 ./...

# Discovers fuzzers via `go test -list 'Fuzz.*'`. If no fuzzers exist, prints
# a friendly note and exits 0 — `make check` does not depend on this target.
test-fuzz:
	@found=0; \
	for pkg in $$($(GO) list ./...); do \
	  if $(GO) test -list 'Fuzz.*' "$$pkg" 2>/dev/null | grep -q '^Fuzz'; then \
	    found=1; \
	    $(GO) test -run='^$$' -fuzz='Fuzz.*' -fuzztime=60s "$$pkg" || exit 1; \
	  fi; \
	done; \
	if [ "$$found" -eq 0 ]; then \
	  echo "no fuzzers found; skipping (pending implementation)."; \
	fi

# ---- lint / vet / fmt -----------------------------------------------------

lint:
	$(GOLANGCILINT) run ./...
	cd $(BDD_DIR) && $(GOLANGCILINT) run ./...

vet:
	$(GO) vet ./...
	cd $(BDD_DIR) && $(GO) vet ./...

fmt:
	$(GOFMT) -s -w .
	$(GOIMPORTS) -local $(MODULE_PATH) -w .

# Asserts the tree is fmt-clean. Any diff from gofmt -s or goimports fails.
fmt-check:
	@out=$$($(GOFMT) -s -l . 2>&1); \
	if [ -n "$$out" ]; then \
	  echo "fmt-check: gofmt -s would reformat:"; \
	  echo "$$out"; \
	  exit 1; \
	fi
	@out=$$($(GOIMPORTS) -local $(MODULE_PATH) -l . 2>&1); \
	if [ -n "$$out" ]; then \
	  echo "fmt-check: goimports would reformat:"; \
	  echo "$$out"; \
	  exit 1; \
	fi
	@echo "OK: fmt-check passed."

# ---- benchmarks -----------------------------------------------------------
#
# bench / bench-compare are INFORMATIONAL only in CI per D-09 (until a
# self-hosted bench runner becomes available, hardware noise on
# GitHub-hosted runners is too high for a blocking PERF-04 gate). Locally
# they run as a developer-driven feedback loop: edit code → `make bench` →
# `make bench-compare` → commit bench.txt if the change is intentional.

# Runs `go test -bench=. -benchmem -count=10` and writes the output to
# $(BENCH_NEW_FILE). Tolerant if no benchmarks exist yet (Phase 2+ adds
# them) — writes a header-only $(BENCH_NEW_FILE) so bench-compare always
# has a file to consume.
bench:
	@found=0; \
	for pkg in $$($(GO) list ./...); do \
	  if $(GO) test -list 'Benchmark.*' "$$pkg" 2>/dev/null | grep -q '^Benchmark'; then \
	    found=1; break; \
	  fi; \
	done; \
	if [ "$$found" -eq 0 ]; then \
	  echo "no benchmarks found; writing empty $(BENCH_NEW_FILE) (pending Phase 2)."; \
	  printf '# bench.txt.new — no benchmarks defined yet (pending Phase 2)\n' > $(BENCH_NEW_FILE); \
	else \
	  $(GO) test -bench=. -benchmem -count=10 ./... | tee $(BENCH_NEW_FILE); \
	fi

# Runs `benchstat $(BENCH_FILE) $(BENCH_NEW_FILE)` to produce an A/B
# regression report. Definitive locally; INFORMATIONAL in CI per D-09 —
# the workflow job sets `continue-on-error: true` so a regression does
# not block PRs until a self-hosted bench runner is available.
#
# Tolerance: if $(BENCH_NEW_FILE) is absent (no `make bench` yet),
# auto-generate an empty placeholder so the comparison runs cleanly.
# `benchstat` tolerates empty input.
bench-compare:
	@if [ ! -f $(BENCH_FILE) ]; then \
	  echo "bench-compare: $(BENCH_FILE) missing — initialised by plan 01-04 with a header-only placeholder."; \
	  exit 1; \
	fi; \
	if [ ! -f $(BENCH_NEW_FILE) ]; then \
	  echo "bench-compare: $(BENCH_NEW_FILE) absent; auto-generating empty placeholder."; \
	  printf '# bench.txt.new — auto-generated by make bench-compare (run `make bench` first for real data)\n' > $(BENCH_NEW_FILE); \
	fi; \
	if command -v $(BENCHSTAT) >/dev/null 2>&1; then \
	  $(BENCHSTAT) $(BENCH_FILE) $(BENCH_NEW_FILE); \
	else \
	  echo "benchstat not installed; install: go install golang.org/x/perf/cmd/benchstat@latest (skipping locally — CI installs it)."; \
	fi

# ---- coverage -------------------------------------------------------------

coverage:
	$(GO) test -race -coverprofile=$(COVERAGE_FILE) -covermode=atomic ./...

# Coverage floor enforcement (plan 01-04 lands the script). Enforces all
# three CLAUDE.md floors:
#   - overall  >= 95%
#   - per-file >= 90%
#   - public-API funcs: 100% (every exported func has at least one
#     non-zero coverage row)
#
# The script is tolerant of the bootstrap state — when coverage.out
# contains no profiled statements (no test files yet), it exits 0 with
# a "pending Phase 2" note. From Phase 2 onwards the floors are
# enforced unconditionally.
## suppress: internal helper invoked by `make check`; not user-facing.
coverage-check:
	bash scripts/verify-coverage-floors.sh $(COVERAGE_FILE)

# ---- modules --------------------------------------------------------------

tidy:
	$(GO) mod tidy
	cd $(BDD_DIR) && $(GO) mod tidy

# Verifies `go mod tidy` is a no-op in both modules; any diff fails CI.
tidy-check:
	$(GO) mod tidy
	cd $(BDD_DIR) && $(GO) mod tidy
	@git diff --exit-code -- go.mod go.sum $(BDD_DIR)/go.mod $(BDD_DIR)/go.sum

# ---- security / vuln ------------------------------------------------------

# Local-developer focus: govulncheck. The definitive gosec scan runs in
# .github/workflows/security.yml with SARIF upload. Tolerant of missing tools.
security:
	@if command -v $(GOVULNCHECK) >/dev/null 2>&1; then \
	  $(GOVULNCHECK) ./...; \
	else \
	  echo "govulncheck not installed; install: go install golang.org/x/vuln/cmd/govulncheck@latest"; \
	fi

# ---- verify-* (CI gates) --------------------------------------------------

# Runtime-deps allowlist gate. The script (plan 01-04) asserts that the
# root go.mod's non-indirect runtime dependency set is exactly
# {github.com/axonops/fuzzymatch, golang.org/x/text}. Adding any other
# runtime dep requires explicit user approval and
# algorithm-licensing-reviewer sign-off per CLAUDE.md.
verify-deps-allowlist:
	bash scripts/verify-no-runtime-deps.sh

# Plan 01-04 lands the golden-form determinism harness. Until then this
# target runs `go test -run TestGolden_` which currently matches no tests.
verify-determinism:
	$(GO) test -run TestGolden_ ./...

verify-license-headers:
	bash scripts/verify-license-headers.sh

# Regenerates testdata/cross-validation/swg/vectors.json by invoking the
# biopython-based generator script. Developer-only — NOT included in
# `make check`. The committed JSON is the verification fixture; CI does
# NOT require Python at test time. Re-run this target when biopython is
# bumped or when new test cases are added to
# scripts/gen-swg-cross-validation.py.
#
# Requires: python3 + biopython 1.85+
#   python3 -m pip install --user biopython
regen-swg-cross-validation:
	@if ! command -v python3 >/dev/null 2>&1; then \
	  echo "python3 not found; install Python 3.x and run: python3 -m pip install --user biopython"; \
	  exit 1; \
	fi
	python3 scripts/gen-swg-cross-validation.py

# Regenerates testdata/cross-validation/ratcliff-obershelp/vectors.json by
# invoking the difflib-based generator script. Developer-only — NOT
# included in `make check`. The committed JSON is the verification fixture;
# CI does NOT require Python at test time. Re-run this target when new test
# cases are added to scripts/gen-ratcliff-obershelp-cross-validation.py.
#
# difflib is Python stdlib — NO pip install needed (the structural
# simplification over the biopython-based SWG generator above).
#
# Requires: python3 (>= 3.7 for dict insertion-order preservation).
regen-ratcliff-obershelp-cross-validation:
	@if ! command -v python3 >/dev/null 2>&1; then \
	  echo "python3 not found; install Python 3.7+ (difflib is stdlib — no pip install needed)"; \
	  exit 1; \
	fi
	python3 scripts/gen-ratcliff-obershelp-cross-validation.py

# Regenerates testdata/cross-validation/token-ratios/vectors.json by
# invoking the rapidfuzz-based generator script. Developer-only — NOT
# included in `make check`. The committed JSON is the verification
# fixture; CI does NOT require Python at test time. Re-run this target
# when rapidfuzz is bumped or when new test cases are added to
# scripts/gen-token-ratio-cross-validation.py. The script refuses to
# run on a non-pinned rapidfuzz version (currently 3.14.5).
#
# Requires: python3 (>= 3.7) + rapidfuzz==3.14.5
#   python3 -m pip install --user rapidfuzz==3.14.5
regen-token-ratio-cross-validation:
	@if ! command -v python3 >/dev/null 2>&1; then \
	  echo "python3 not found; install Python 3.7+ and run: python3 -m pip install --user rapidfuzz==3.14.5"; \
	  exit 1; \
	fi
	python3 scripts/gen-token-ratio-cross-validation.py

# Regenerates testdata/cross-validation/phonetic/vectors.json by invoking the
# dual-pin generator script (jellyfish==1.2.1 + Metaphone==0.6). Developer-only
# — NOT included in `make check`. The committed JSON is the verification fixture;
# CI does NOT require Python at test time. Re-run this target when the pin
# versions are bumped or when new phonetic test cases are added to
# scripts/gen-phonetic-cross-validation.py. The script refuses to run on a
# non-pinned version of either package (JELLYFISH_VERSION = "1.2.1" and
# METAPHONE_VERSION = "0.6").
#
# OQ-1 RESOLUTION LOCKED 2026-05-15: Two pins are required because jellyfish
# 1.x has no Double Metaphone; the Metaphone package (oubiwann, BSD-3-Clause)
# carries Double Metaphone instead. See plan 07-01 SUMMARY and RESEARCH.md §4.
#
# Requires: python3 (>= 3.7) + jellyfish==1.2.1 + Metaphone==0.6
#   python3 -m pip install --user jellyfish==1.2.1 Metaphone==0.6
regen-phonetic-cross-validation:
	@if ! command -v python3 >/dev/null 2>&1; then \
	  echo "python3 not found; install Python 3.7+ and run: python3 -m pip install --user jellyfish==1.2.1 Metaphone==0.6"; \
	  exit 1; \
	fi
	python3 scripts/gen-phonetic-cross-validation.py

# Regenerates testdata/cross-validation/character/vectors.json by invoking the
# jellyfish==1.2.1 generator script. Developer-only — NOT included in
# `make check`. The committed JSON is the verification fixture; CI does NOT
# require Python at test time. Re-run this target when the pinned jellyfish
# version is bumped or when new test cases are added to
# scripts/gen-character-cross-validation.py. The script refuses to run on
# a non-pinned jellyfish version (JELLYFISH_VERSION = "1.2.1") — version
# is probed via `pip show jellyfish` because jellyfish 1.2.1 dropped its
# module-level __version__ attribute.
#
# Plan 08.5-10 task 1 lands the character-tier cross-validation corpus
# (Levenshtein, Damerau-OSA, Jaro, JaroWinkler — the four jellyfish
# surfaces). See CONTRIBUTING.md "Cross-validation corpora" for the
# pin-bump protocol.
#
# Requires: python3 (>= 3.7) + jellyfish==1.2.1
#   python3 -m pip install --user jellyfish==1.2.1
regen-character-cross-validation:
	@if ! command -v python3 >/dev/null 2>&1; then \
	  echo "python3 not found; install Python 3.7+ and run: python3 -m pip install --user jellyfish==1.2.1"; \
	  exit 1; \
	fi
	python3 scripts/gen-character-cross-validation.py

# Regenerates testdata/cross-validation/qgram/vectors.json by invoking the
# py_stringmatching==0.4.7 generator script. Developer-only — NOT included
# in `make check`. The committed JSON is the verification fixture; CI does
# NOT require Python at test time. Re-run this target when the pinned
# py_stringmatching version is bumped or when new test cases are added to
# scripts/gen-qgram-cross-validation.py. The script refuses to run on a
# non-pinned py_stringmatching version (PYSM_VERSION = "0.4.7").
#
# Plan 08.5-10 task 2 lands the q-gram-tier cross-validation corpus
# (Q-Gram Jaccard, Sørensen-Dice, Cosine, Tversky — the four q-gram
# surfaces). Inputs are restricted to q-gram-unique extractions so
# py_stringmatching's SET semantics and fuzzymatch's MULTISET semantics
# coincide; see scripts/gen-qgram-cross-validation.py module docstring
# "set-vs-multiset DIVERGENCE" for the full rationale.
#
# Requires: python3 (>= 3.7) + py_stringmatching==0.4.7
#   python3 -m pip install --user py_stringmatching==0.4.7
regen-qgram-cross-validation:
	@if ! command -v python3 >/dev/null 2>&1; then \
	  echo "python3 not found; install Python 3.7+ and run: python3 -m pip install --user py_stringmatching==0.4.7"; \
	  exit 1; \
	fi
	python3 scripts/gen-qgram-cross-validation.py

# Plan 01-03 lands .goreleaser.yml. Until then this is a tolerant no-op.
release-check:
	@if [ -f .goreleaser.yml ]; then \
	  if command -v $(GORELEASER) >/dev/null 2>&1; then \
	    $(GORELEASER) check; \
	  else \
	    echo "goreleaser not installed; install per docs/CONTRIBUTING (plan 01-08)."; \
	  fi; \
	else \
	  echo "pending plan 01-03: .goreleaser.yml not yet present."; \
	fi

# ---- housekeeping ---------------------------------------------------------

clean:
	$(GO) clean ./...
	rm -f $(COVERAGE_FILE) $(BENCH_NEW_FILE)
