// Copyright 2026 AxonOps Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// monge_elkan_cross_validation_test.go asserts agreement between the
// project's MongeElkanScore (asymmetric) and MongeElkanScoreSymmetric
// (symmetric) surfaces — both with JaroWinkler-inner and
// Levenshtein-inner — against the py_stringmatching==0.4.7 reference
// corpus committed at testdata/cross-validation/monge-elkan/vectors.json.
// The corpus carries four scores per entry — monge_elkan_asymmetric_jw,
// monge_elkan_asymmetric_lev, monge_elkan_symmetric_jw,
// monge_elkan_symmetric_lev — emitted by
// scripts/gen-monge-elkan-cross-validation.py with the py_stringmatching
// version pinned to PYSM_VERSION = "0.4.7". The symmetric scores are
// computed in Python as (forward + reverse) / 2 since py_stringmatching
// does not expose a symmetric Monge-Elkan primitive.
//
// Tolerance:
//
//   - Levenshtein-inner surfaces (monge_elkan_asymmetric_lev,
//     monge_elkan_symmetric_lev): 1e-9. Levenshtein-as-similarity is
//     1 - dist/max_len — pure-integer + single division, fp64-clean
//     across both libraries.
//   - JaroWinkler-inner surfaces (monge_elkan_asymmetric_jw,
//     monge_elkan_symmetric_jw): 1e-6. py_stringmatching's JaroWinkler
//     uses float32 for some intermediate computations (confirmed by
//     direct probe: JaroWinkler().get_sim_score("john", "johnathan")
//     == 0.8888888955116272 vs fuzzymatch's float64 0.8888888888888889
//     — an fp32-vs-fp64 difference of ~6.6e-9 per token comparison).
//     Monge-Elkan accumulates these differences across the per-token
//     max-of-sim reduction; the relaxed tolerance accommodates the
//     accumulated drift. The Go-side fuzzymatch surface is fp64-clean
//     throughout (project determinism guarantees); the divergence is
//     entirely an artefact of py_stringmatching's internal precision.
//
// Tokeniser-divergence handling:
//
//	The corpus is restricted to whitespace-separated lowercase ASCII
//	inputs so fuzzymatch's Tokenise(DefaultTokeniseOptions()) and the
//	Python script's str.split() produce identical token lists. See the
//	generator's _assert_corpus_is_tokenise_safe gate for the
//	constraint. This mirrors the OQ-1 resolution in
//	gen-token-ratio-cross-validation.py.
//
// Inner-metric coverage:
//
//	The corpus exercises TWO of fuzzymatch's 14 permitted Monge-Elkan
//	inner metrics: AlgoJaroWinkler (the DEFAULT inner per 06-CONTEXT.md
//	§4 LOCKED — load-bearing for the dispatch slot AlgoMongeElkan) and
//	AlgoLevenshtein (representative of the integer-distance-divided-by-
//	max-len family). The other 12 permitted inners are covered by
//	primary-source reference vectors in monge_elkan_test.go.
//
// The corpus is regenerated by `make regen-monge-elkan-cross-validation`
// (developer-only — requires `pip install py_stringmatching==0.4.7`).
// CI does NOT require Python at test time; the committed JSON is the
// verification fixture read directly by Go.
//
// Failure messages include the py_stringmatching_version, python_version,
// inner-metric name, asymmetric-or-symmetric flag, and tolerance used
// for triage — same pattern as
// token_ratio_cross_validation_test.go::TestTokenRatios_CrossValidation.

package fuzzymatch_test

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/axonops/fuzzymatch"
)

// mongeElkanCrossValidationEpsilonLevenshtein is the tolerance for the
// two Levenshtein-inner surfaces. Pure-integer + division → fp64-clean
// across both libraries; 1e-9 matches the project-wide convention.
const mongeElkanCrossValidationEpsilonLevenshtein = 1e-9

// mongeElkanCrossValidationEpsilonJaroWinkler is the tolerance for the
// two JaroWinkler-inner surfaces. py_stringmatching's JaroWinkler uses
// float32 internally; Monge-Elkan accumulates fp32-vs-fp64 differences
// of ~6.6e-9 per token comparison across the per-token max-of-sim
// reduction. The 1e-6 tolerance accommodates the accumulated drift —
// see file header for the precision-analysis rationale.
const mongeElkanCrossValidationEpsilonJaroWinkler = 1e-6

// mongeElkanEntry is one entry in the committed
// testdata/cross-validation/monge-elkan/vectors.json corpus produced by
// scripts/gen-monge-elkan-cross-validation.py.
type mongeElkanEntry struct {
	Name                    string  `json:"name"`
	A                       string  `json:"a"`
	B                       string  `json:"b"`
	MongeElkanAsymmetricJW  float64 `json:"monge_elkan_asymmetric_jw"`
	MongeElkanAsymmetricLev float64 `json:"monge_elkan_asymmetric_lev"`
	MongeElkanSymmetricJW   float64 `json:"monge_elkan_symmetric_jw"`
	MongeElkanSymmetricLev  float64 `json:"monge_elkan_symmetric_lev"`
}

// mongeElkanMetadata is the top-level _metadata block — pins the
// generator's py_stringmatching version, the Python version that
// produced the corpus, and the regeneration timestamp.
type mongeElkanMetadata struct {
	PyStringMatchingVersion string `json:"py_stringmatching_version"`
	PythonVersion           string `json:"python_version"`
	RegeneratedAt           string `json:"regenerated_at"`
}

// mongeElkanCorpus is the top-level shape of the corpus JSON file.
type mongeElkanCorpus struct {
	Version  int                `json:"version"`
	Metadata mongeElkanMetadata `json:"_metadata"`
	Entries  []mongeElkanEntry  `json:"entries"`
}

// TestMongeElkan_CrossValidation asserts agreement between the project's
// MongeElkanScore (asymmetric) and MongeElkanScoreSymmetric surfaces with
// JaroWinkler-inner and Levenshtein-inner, against py_stringmatching's
// MongeElkan(JaroWinkler().get_sim_score) and MongeElkan(Levenshtein().
// get_sim_score) reference outputs.
//
// Surface mapping (corpus → fuzzymatch):
//
//	monge_elkan_asymmetric_jw  → MongeElkanScore(a, b, AlgoJaroWinkler, opts)
//	monge_elkan_asymmetric_lev → MongeElkanScore(a, b, AlgoLevenshtein, opts)
//	monge_elkan_symmetric_jw   → MongeElkanScoreSymmetric(a, b, AlgoJaroWinkler, opts)
//	monge_elkan_symmetric_lev  → MongeElkanScoreSymmetric(a, b, AlgoLevenshtein, opts)
//
// opts is DefaultNormalisationOptions() (the dispatch-slot default).
func TestMongeElkan_CrossValidation(t *testing.T) {
	path := filepath.Join("testdata", "cross-validation", "monge-elkan", "vectors.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("TestMongeElkan_CrossValidation: read %s: %v (regenerate with `make regen-monge-elkan-cross-validation`)", path, err)
	}
	var c mongeElkanCorpus
	if err := json.Unmarshal(raw, &c); err != nil {
		t.Fatalf("TestMongeElkan_CrossValidation: parse %s: %v", path, err)
	}
	if c.Version != 1 {
		t.Fatalf("TestMongeElkan_CrossValidation: unsupported corpus version %d (want 1)", c.Version)
	}
	if len(c.Entries) == 0 {
		t.Fatalf("TestMongeElkan_CrossValidation: empty corpus")
	}
	if c.Metadata.PyStringMatchingVersion == "" {
		t.Fatalf("TestMongeElkan_CrossValidation: corpus missing _metadata.py_stringmatching_version — regenerate with `make regen-monge-elkan-cross-validation`")
	}
	if c.Metadata.PythonVersion == "" {
		t.Fatalf("TestMongeElkan_CrossValidation: corpus missing _metadata.python_version — regenerate with `make regen-monge-elkan-cross-validation`")
	}

	// Python >= 3.7 gate.
	parts := strings.SplitN(c.Metadata.PythonVersion, ".", 3)
	if len(parts) < 2 {
		t.Fatalf("TestMongeElkan_CrossValidation: malformed python_version %q (want major.minor[.patch])", c.Metadata.PythonVersion)
	}
	major, err1 := strconv.Atoi(parts[0])
	minor, err2 := strconv.Atoi(parts[1])
	if err1 != nil || err2 != nil {
		t.Fatalf("TestMongeElkan_CrossValidation: non-numeric python_version %q", c.Metadata.PythonVersion)
	}
	if major < 3 || (major == 3 && minor < 7) {
		t.Fatalf("TestMongeElkan_CrossValidation: corpus generated with Python %s; script minimum is 3.7", c.Metadata.PythonVersion)
	}

	opts := fuzzymatch.DefaultNormalisationOptions()

	for _, e := range c.Entries {
		e := e // local copy for the closure

		// Asymmetric JaroWinkler-inner.
		t.Run(e.Name+"/asymmetric/jaro_winkler", func(t *testing.T) {
			got := fuzzymatch.MongeElkanScore(e.A, e.B, fuzzymatch.AlgoJaroWinkler, opts)
			delta := math.Abs(got - e.MongeElkanAsymmetricJW)
			if delta > mongeElkanCrossValidationEpsilonJaroWinkler {
				t.Errorf("MongeElkanScore(%q, %q, AlgoJaroWinkler) = %.17g; py_stringmatching MongeElkan(JaroWinkler) = %.17g (delta %.2e, tol %g [jw-inner: py32-vs-go64], pysm %s, python %s)",
					e.A, e.B, got, e.MongeElkanAsymmetricJW, delta, mongeElkanCrossValidationEpsilonJaroWinkler,
					c.Metadata.PyStringMatchingVersion, c.Metadata.PythonVersion)
			}
		})

		// Asymmetric Levenshtein-inner.
		t.Run(e.Name+"/asymmetric/levenshtein", func(t *testing.T) {
			got := fuzzymatch.MongeElkanScore(e.A, e.B, fuzzymatch.AlgoLevenshtein, opts)
			delta := math.Abs(got - e.MongeElkanAsymmetricLev)
			if delta > mongeElkanCrossValidationEpsilonLevenshtein {
				t.Errorf("MongeElkanScore(%q, %q, AlgoLevenshtein) = %.17g; py_stringmatching MongeElkan(Levenshtein) = %.17g (delta %.2e, tol %g, pysm %s, python %s)",
					e.A, e.B, got, e.MongeElkanAsymmetricLev, delta, mongeElkanCrossValidationEpsilonLevenshtein,
					c.Metadata.PyStringMatchingVersion, c.Metadata.PythonVersion)
			}
		})

		// Symmetric JaroWinkler-inner.
		t.Run(e.Name+"/symmetric/jaro_winkler", func(t *testing.T) {
			got := fuzzymatch.MongeElkanScoreSymmetric(e.A, e.B, fuzzymatch.AlgoJaroWinkler, opts)
			delta := math.Abs(got - e.MongeElkanSymmetricJW)
			if delta > mongeElkanCrossValidationEpsilonJaroWinkler {
				t.Errorf("MongeElkanScoreSymmetric(%q, %q, AlgoJaroWinkler) = %.17g; reference symmetric MongeElkan(JaroWinkler) = %.17g (delta %.2e, tol %g [jw-inner: py32-vs-go64], pysm %s, python %s)",
					e.A, e.B, got, e.MongeElkanSymmetricJW, delta, mongeElkanCrossValidationEpsilonJaroWinkler,
					c.Metadata.PyStringMatchingVersion, c.Metadata.PythonVersion)
			}
		})

		// Symmetric Levenshtein-inner.
		t.Run(e.Name+"/symmetric/levenshtein", func(t *testing.T) {
			got := fuzzymatch.MongeElkanScoreSymmetric(e.A, e.B, fuzzymatch.AlgoLevenshtein, opts)
			delta := math.Abs(got - e.MongeElkanSymmetricLev)
			if delta > mongeElkanCrossValidationEpsilonLevenshtein {
				t.Errorf("MongeElkanScoreSymmetric(%q, %q, AlgoLevenshtein) = %.17g; reference symmetric MongeElkan(Levenshtein) = %.17g (delta %.2e, tol %g, pysm %s, python %s)",
					e.A, e.B, got, e.MongeElkanSymmetricLev, delta, mongeElkanCrossValidationEpsilonLevenshtein,
					c.Metadata.PyStringMatchingVersion, c.Metadata.PythonVersion)
			}
		})
	}
}

// TestMongeElkan_CrossValidation_CorpusShape asserts the committed
// corpus contains at least 30 entries spanning the categories promised
// by plan 08.5-10 task 3:
//
//   - identity / both-empty / one-empty (≥ 3)
//   - single-token pairs (≥ 1 — checked via "single_token_" prefix)
//   - equal-token-count pairs (≥ 1 — checked via "two_token_equal_count"
//     or "three_token_equal_count")
//   - asymmetric (unequal-token-count) pairs (≥ 1 — checked via "asym_"
//     prefix)
//   - subset pairs (≥ 1 — checked via "subset_" prefix)
//   - disjoint pairs (≥ 1 — checked via "disjoint_" prefix)
//   - name-style pairs (≥ 1 — checked via "name_match_" prefix)
//   - sentence-style pairs (≥ 1 — checked via "sentence_" prefix)
//   - long multi-token pairs (≥ 1 — checked via "long_six_token_" prefix)
//
// Together with TestMongeElkan_CrossValidation, this shape gate prevents
// future trimming of load-bearing fixtures.
func TestMongeElkan_CrossValidation_CorpusShape(t *testing.T) {
	path := filepath.Join("testdata", "cross-validation", "monge-elkan", "vectors.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	var c mongeElkanCorpus
	if err := json.Unmarshal(raw, &c); err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}

	if len(c.Entries) < 30 {
		t.Errorf("corpus has %d entries; want >= 30 (plan 08.5-10 task 3 success criterion)", len(c.Entries))
	}

	if c.Metadata.PyStringMatchingVersion != "0.4.7" {
		t.Errorf("corpus _metadata.py_stringmatching_version = %q; want %q (the pinned version per plan 08.5-10)", c.Metadata.PyStringMatchingVersion, "0.4.7")
	}

	categories := map[string]bool{
		"identity":        false,
		"both_empty":      false,
		"one_empty":       false,
		"single_token_":   false,
		"_token_equal_":   false,
		"asym_":           false,
		"subset_":         false,
		"disjoint_":       false,
		"name_match_":     false,
		"sentence_":       false,
		"long_six_token_": false,
	}
	for _, e := range c.Entries {
		for cat := range categories {
			if strings.Contains(e.Name, cat) {
				categories[cat] = true
			}
		}
	}
	for cat, found := range categories {
		if !found {
			t.Errorf("corpus is missing the %q category (no entry name contains the substring) — was a load-bearing fixture trimmed?", cat)
		}
	}
}
