// Copyright 2026 AxonOps Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// phonetic_cross_validation_test.go asserts agreement between the project's
// phonetic algorithms and the dual-pin cross-validation corpus committed at
// testdata/cross-validation/phonetic/vectors.json. The corpus was generated
// by scripts/gen-phonetic-cross-validation.py with:
//
//   - jellyfish==1.2.1  for Soundex, NYSIIS, MRA
//   - Metaphone==0.6    for Double Metaphone
//
// OQ-1 RESOLUTION LOCKED 2026-05-15: jellyfish 1.x has no Double Metaphone
// implementation; metaphone (oubiwann, BSD-3-Clause) carries it instead.
// This is a USER-AUTHORIZED amendment to CONTEXT.md §1's implicit single-pin
// assumption, recorded in plan 07-01 SUMMARY.
//
// Variant-divergence handling: entries carrying variant_divergence=true have
// the Knuth/Taft/NBS-expected value in the "code"/"primary"/"secondary" field
// and the jellyfish value in "divergent_jellyfish_value". The loader asserts
// our implementation matches the EXPECTED value (not the jellyfish value).
//
// Wave plan mapping:
//   - Soundex sub-test ASSERTS (plan 07-01 — this plan)
//   - DoubleMetaphone sub-test: t.Skip (enabled by plan 07-02)
//   - NYSIIS sub-test: t.Skip (enabled by plan 07-03)
//   - MRA sub-test: t.Skip (enabled by plan 07-04)
//
// The corpus is regenerated by `make regen-phonetic-cross-validation`
// (developer-only — requires pip install jellyfish==1.2.1 Metaphone==0.6).
// CI does NOT require Python at test time; the committed JSON is the
// verification fixture read directly by Go.

package fuzzymatch_test

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/axonops/fuzzymatch"
)

// phoneticEntry is one entry in the committed cross-validation corpus.
// The Code field carries the phonetic code for Soundex/NYSIIS/MRA entries.
// Primary and Secondary carry the two keys for DoubleMetaphone entries.
// omitempty on both groups allows a single struct to represent both shapes.
type phoneticEntry struct {
	Algorithm             string `json:"algorithm"`
	Input                 string `json:"input"`
	Branch                string `json:"branch,omitempty"`
	Code                  string `json:"code,omitempty"`
	Primary               string `json:"primary,omitempty"`
	Secondary             string `json:"secondary,omitempty"`
	VariantDivergence     bool   `json:"variant_divergence,omitempty"`
	DivergentJellyfishVal string `json:"divergent_jellyfish_value,omitempty"`
}

// phoneticMetadata is the top-level _metadata block — pins both generator
// package versions, the Python version that produced the corpus, and the
// regeneration timestamp (informational — not asserted for byte-stability).
type phoneticMetadata struct {
	JellyfishVersion string `json:"jellyfish_version"`
	MetaphoneVersion string `json:"metaphone_version"`
	PythonVersion    string `json:"python_version"`
	RegeneratedAt    string `json:"regenerated_at"`
	ScriptSHA256     string `json:"script_sha256"`
}

// phoneticCorpus is the top-level shape of the corpus JSON file — see
// scripts/gen-phonetic-cross-validation.py for the generator schema.
type phoneticCorpus struct {
	Version  int              `json:"version"`
	Metadata phoneticMetadata `json:"_metadata"`
	Entries  []phoneticEntry  `json:"entries"`
}

// TestPhonetic_CrossValidation asserts agreement between the project's phonetic
// algorithms and the dual-pin corpus (jellyfish==1.2.1 + Metaphone==0.6).
// Four per-algorithm t.Run sub-tests; Soundex is active in plan 07-01;
// DM/NYSIIS/MRA are stubbed with t.Skip for plans 07-02..07-04.
func TestPhonetic_CrossValidation(t *testing.T) {
	path := filepath.Join("testdata", "cross-validation", "phonetic", "vectors.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("TestPhonetic_CrossValidation: read %s: %v (regenerate with `make regen-phonetic-cross-validation`)", path, err)
	}
	var c phoneticCorpus
	if err := json.Unmarshal(raw, &c); err != nil {
		t.Fatalf("TestPhonetic_CrossValidation: parse %s: %v", path, err)
	}
	if c.Version != 1 {
		t.Fatalf("TestPhonetic_CrossValidation: unsupported corpus version %d (want 1)", c.Version)
	}
	if len(c.Entries) == 0 {
		t.Fatalf("TestPhonetic_CrossValidation: empty corpus — regenerate with `make regen-phonetic-cross-validation`")
	}

	// Dual version-pin preamble: both jellyfish AND metaphone versions must
	// match the locked pins per OQ-1 RESOLUTION LOCKED 2026-05-15.
	const wantJellyfish = "1.2.1"
	const wantMetaphone = "0.6"
	if c.Metadata.JellyfishVersion != wantJellyfish {
		t.Fatalf("TestPhonetic_CrossValidation: corpus _metadata.jellyfish_version = %q; want %q — regenerate with `make regen-phonetic-cross-validation` using jellyfish==%s",
			c.Metadata.JellyfishVersion, wantJellyfish, wantJellyfish)
	}
	if c.Metadata.MetaphoneVersion != wantMetaphone {
		t.Fatalf("TestPhonetic_CrossValidation: corpus _metadata.metaphone_version = %q; want %q — regenerate with `make regen-phonetic-cross-validation` using Metaphone==%s",
			c.Metadata.MetaphoneVersion, wantMetaphone, wantMetaphone)
	}
	if c.Metadata.PythonVersion == "" {
		t.Fatalf("TestPhonetic_CrossValidation: corpus missing _metadata.python_version — regenerate with `make regen-phonetic-cross-validation`")
	}

	// Per-algorithm sub-tests. Use t.Run(entry.Algorithm+"/"+entry.Input)
	// to give each entry its own failure line in go test output.
	t.Run("Soundex", func(t *testing.T) {
		n := 0
		for _, e := range c.Entries {
			e := e
			if e.Algorithm != "Soundex" {
				continue
			}
			n++
			t.Run(e.Input, func(t *testing.T) {
				got := fuzzymatch.SoundexCode(e.Input)
				if got != e.Code {
					if e.VariantDivergence {
						t.Errorf("SoundexCode(%q) = %q; want %q (Knuth/Census expected; jellyfish divergent value = %q)",
							e.Input, got, e.Code, e.DivergentJellyfishVal)
					} else {
						t.Errorf("SoundexCode(%q) = %q; want %q (jellyfish %s cross-validation)",
							e.Input, got, e.Code, c.Metadata.JellyfishVersion)
					}
				}
			})
		}
		if n == 0 {
			t.Fatal("no Soundex entries in corpus — corpus may be empty or corrupted")
		}
	})

	t.Run("DoubleMetaphone", func(t *testing.T) {
		// Branch-count guard: verify corpus has minimum coverage per branch
		// before per-entry assertions. Build map[branch]count first.
		// The map is iterated for assertion only (not ordered output) — DET-03 honoured.
		branchCount := make(map[string]int)
		for _, e := range c.Entries {
			if e.Algorithm == "DoubleMetaphone" && e.Branch != "" && e.Branch != "edge" {
				branchCount[e.Branch]++
			}
		}
		majorBranches := []string{"germanic", "slavic", "romance", "greek"}
		for _, branch := range majorBranches {
			if branchCount[branch] < 7 {
				t.Errorf("DoubleMetaphone branch %q: %d entries; want >= 7", branch, branchCount[branch])
			}
		}
		if branchCount["chinese-origin"] < 4 {
			t.Errorf("DoubleMetaphone branch %q: %d entries; want >= 4", "chinese-origin", branchCount["chinese-origin"])
		}

		// Per-entry primary + secondary equality assertions.
		n := 0
		for _, e := range c.Entries {
			e := e
			if e.Algorithm != "DoubleMetaphone" {
				continue
			}
			n++
			t.Run(e.Input, func(t *testing.T) {
				gotP, gotS := fuzzymatch.DoubleMetaphoneKeys(e.Input)
				if gotP != e.Primary {
					t.Errorf("DoubleMetaphoneKeys(%q).primary = %q; want %q (branch=%s, metaphone==%s cross-validation)",
						e.Input, gotP, e.Primary, e.Branch, c.Metadata.MetaphoneVersion)
				}
				if gotS != e.Secondary {
					t.Errorf("DoubleMetaphoneKeys(%q).secondary = %q; want %q (branch=%s, metaphone==%s cross-validation)",
						e.Input, gotS, e.Secondary, e.Branch, c.Metadata.MetaphoneVersion)
				}
			})
		}
		if n == 0 {
			t.Fatal("no DoubleMetaphone entries in corpus — corpus may be empty or corrupted")
		}
	})

	t.Run("NYSIIS", func(t *testing.T) {
		// NYSIIS cross-validation against jellyfish==1.2.1.
		// Entries where jellyfish emits >6 chars (modified-NYSIIS variant)
		// carry variant_divergence=true; the loader asserts against the
		// TRUNCATED Taft-1970 value (entry.Code), NOT the jellyfish value
		// (entry.DivergentJellyfishVal). See RESEARCH.md §7 Pitfall 7.B.
		n := 0
		divergenceCount := 0
		for _, e := range c.Entries {
			e := e
			if e.Algorithm != "NYSIIS" {
				continue
			}
			n++
			if e.VariantDivergence {
				divergenceCount++
			}
			t.Run(e.Input, func(t *testing.T) {
				got := fuzzymatch.NYSIISCode(e.Input)
				if got != e.Code {
					if e.VariantDivergence {
						t.Errorf(
							"NYSIISCode(%q) = %q; want %q (Taft-1970 truncated value; jellyfish divergent value = %q, variant_divergence=true)",
							e.Input, got, e.Code, e.DivergentJellyfishVal)
					} else {
						t.Errorf("NYSIISCode(%q) = %q; want %q (jellyfish %s cross-validation)",
							e.Input, got, e.Code, c.Metadata.JellyfishVersion)
					}
				}
			})
		}
		if n == 0 {
			t.Fatal("no NYSIIS entries in corpus — corpus may be empty or corrupted")
		}
		// RESEARCH.md key finding 3: ~40-60% of NYSIIS corpus entries carry
		// variant_divergence: true (jellyfish's untruncated output exceeds 6 chars).
		divergencePct := float64(divergenceCount) / float64(n) * 100
		if divergencePct < 30 || divergencePct > 70 {
			t.Logf("NYSIIS variant_divergence rate = %.0f%% (%d/%d); expected ~40-60%% per RESEARCH.md key finding 3",
				divergencePct, divergenceCount, n)
		}
	})

	t.Run("MRA", func(t *testing.T) {
		t.Skip("enabled by plan 07-04")
	})
}
