// Copyright 2026 AxonOps Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// qgram_cross_validation_test.go asserts agreement between the project's
// q-gram-tier surfaces (QGramJaccardScore, SorensenDiceScore, CosineScore,
// TverskyScore) and the py_stringmatching==0.4.7 reference corpus
// committed at testdata/cross-validation/qgram/vectors.json. The corpus
// carries four scores per entry at q=2 (and optionally q=3) — emitted by
// scripts/gen-qgram-cross-validation.py with the py_stringmatching
// version pinned to PYSM_VERSION = "0.4.7".
//
// Tolerance: |our_score - reference_score| <= 1e-9 for Jaccard, Dice,
// Tversky. For Cosine the tolerance is slightly relaxed to 1e-12
// (Cosine's intermediate Σ count_a · count_b / (sqrt(Σ count_a²) ·
// sqrt(Σ count_b²)) involves three multiplications and two sqrt calls;
// the project's deterministic sqrt-based reduction may differ from
// py_stringmatching's NumPy-backed reduction by a small number of ulps).
// In practice both libraries are q-gram-set-of-unique-elements based on
// this corpus, so the count vectors are all-ones and the reductions
// produce identical bits — the relaxed tolerance is defence-in-depth.
//
// set-vs-multiset divergence (LOCKED 2026-05-17 plan 08.5-10):
//
//	py_stringmatching's Jaccard / Dice / Cosine / TverskyIndex treat the
//	input token lists as SETS (duplicates collapse). fuzzymatch's q-gram
//	surfaces treat the q-gram extraction as a MULTISET (Ukkonen 1992,
//	min/max over counts). The corpus is restricted to INPUTS WHOSE q-gram
//	EXTRACTIONS HAVE NO DUPLICATES at the chosen q — the generator's
//	_assert_qgram_unique gate enforces this so set / multiset semantics
//	coincide. See scripts/gen-qgram-cross-validation.py for the full
//	rationale. The fuzzymatch-multiset surface is exercised by
//	q-gram-duplicate fixtures in qgram_jaccard_test.go (primary-source
//	reference vectors).
//
// The corpus is regenerated by `make regen-qgram-cross-validation`
// (developer-only — requires `pip install py_stringmatching==0.4.7`).
// CI does NOT require Python at test time; the committed JSON is the
// verification fixture read directly by Go.
//
// Failure messages include the py_stringmatching_version, python_version,
// q value, and surface field name for triage — same pattern as
// token_ratio_cross_validation_test.go::TestTokenRatios_CrossValidation.

package fuzzymatch_test

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/axonops/fuzzymatch"
)

// qgramCrossValidationEpsilonStandard is the float-comparison tolerance
// for the Jaccard / Dice / Tversky surfaces. 1e-9 matches the Phase 3
// SWG / Phase 4 Ratcliff-Obershelp / Phase 6 token-ratio epsilon
// conventions.
const qgramCrossValidationEpsilonStandard = 1e-9

// qgramCrossValidationEpsilonCosine is the relaxed tolerance for Cosine.
// Cosine's three-multiply-two-sqrt reduction can produce a small number
// of ulps of difference between fuzzymatch's deterministic kernel and
// py_stringmatching's NumPy-backed reduction. The corpus is restricted
// to q-gram-unique inputs (all-ones count vectors), so in practice the
// reductions produce identical bits, but the relaxed tolerance is
// defence-in-depth against future numerical paths.
const qgramCrossValidationEpsilonCosine = 1e-12

// qgramQ2Scores carries the four reference scores at q=2 for one corpus
// entry. The same shape is reused for q3 via a *qgramQ2Scores pointer
// (nil → q=3 not computed for this entry per skip_q3 in the generator).
type qgramQ2Scores struct {
	QGramJaccard float64 `json:"qgram_jaccard"`
	SorensenDice float64 `json:"sorensen_dice"`
	Cosine       float64 `json:"cosine"`
	Tversky      float64 `json:"tversky"`
}

// qgramEntry is one entry in the committed
// testdata/cross-validation/qgram/vectors.json corpus produced by
// scripts/gen-qgram-cross-validation.py.
type qgramEntry struct {
	Name string         `json:"name"`
	A    string         `json:"a"`
	B    string         `json:"b"`
	Q2   qgramQ2Scores  `json:"q2"`
	Q3   *qgramQ2Scores `json:"q3"`
}

// qgramMetadata is the top-level _metadata block — pins the generator's
// py_stringmatching version, the Python version that produced the
// corpus, the Tversky (alpha, beta) parameters, and the regeneration
// timestamp.
type qgramMetadata struct {
	PyStringMatchingVersion string  `json:"py_stringmatching_version"`
	PythonVersion           string  `json:"python_version"`
	TverskyAlpha            float64 `json:"tversky_alpha"`
	TverskyBeta             float64 `json:"tversky_beta"`
	RegeneratedAt           string  `json:"regenerated_at"`
}

// qgramCorpus is the top-level shape of the corpus JSON file.
type qgramCorpus struct {
	Version  int           `json:"version"`
	Metadata qgramMetadata `json:"_metadata"`
	Entries  []qgramEntry  `json:"entries"`
}

// TestQGram_CrossValidation asserts agreement between the project's
// QGramJaccardScore / SorensenDiceScore / CosineScore / TverskyScore
// surfaces and py_stringmatching==0.4.7's reference outputs over q=2 and
// q=3.
//
// Surface mapping (corpus → fuzzymatch):
//
//	q2.qgram_jaccard / q3.qgram_jaccard → QGramJaccardScore(a, b, q)
//	q2.sorensen_dice / q3.sorensen_dice → SorensenDiceScore(a, b, q)
//	q2.cosine        / q3.cosine        → CosineScore(a, b, q)
//	q2.tversky       / q3.tversky       → TverskyScore(a, b, q, α, β)
//
// The corpus is restricted to q-gram-unique inputs so set semantics
// (py_stringmatching) and multiset semantics (fuzzymatch) coincide — see
// file header for the divergence rationale.
func TestQGram_CrossValidation(t *testing.T) {
	path := filepath.Join("testdata", "cross-validation", "qgram", "vectors.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("TestQGram_CrossValidation: read %s: %v (regenerate with `make regen-qgram-cross-validation`)", path, err)
	}
	var c qgramCorpus
	if err := json.Unmarshal(raw, &c); err != nil {
		t.Fatalf("TestQGram_CrossValidation: parse %s: %v", path, err)
	}
	if c.Version != 1 {
		t.Fatalf("TestQGram_CrossValidation: unsupported corpus version %d (want 1)", c.Version)
	}
	if len(c.Entries) == 0 {
		t.Fatalf("TestQGram_CrossValidation: empty corpus")
	}
	if c.Metadata.PyStringMatchingVersion == "" {
		t.Fatalf("TestQGram_CrossValidation: corpus missing _metadata.py_stringmatching_version — regenerate with `make regen-qgram-cross-validation`")
	}
	if c.Metadata.PythonVersion == "" {
		t.Fatalf("TestQGram_CrossValidation: corpus missing _metadata.python_version — regenerate with `make regen-qgram-cross-validation`")
	}

	// Python >= 3.7 gate, mirrors the generator-side _check_python_version.
	parts := strings.SplitN(c.Metadata.PythonVersion, ".", 3)
	if len(parts) < 2 {
		t.Fatalf("TestQGram_CrossValidation: malformed python_version %q (want major.minor[.patch])", c.Metadata.PythonVersion)
	}
	major, err1 := strconv.Atoi(parts[0])
	minor, err2 := strconv.Atoi(parts[1])
	if err1 != nil || err2 != nil {
		t.Fatalf("TestQGram_CrossValidation: non-numeric python_version %q", c.Metadata.PythonVersion)
	}
	if major < 3 || (major == 3 && minor < 7) {
		t.Fatalf("TestQGram_CrossValidation: corpus generated with Python %s; script minimum is 3.7", c.Metadata.PythonVersion)
	}

	// Pin the Tversky parameters; if a future regeneration changes them,
	// the per-entry comparison would still pass on entries where (α, β)
	// happens to be symmetric, but the metadata gate catches the drift
	// up-front.
	if c.Metadata.TverskyAlpha != 0.5 || c.Metadata.TverskyBeta != 0.5 {
		t.Fatalf("TestQGram_CrossValidation: corpus _metadata.tversky_alpha/beta = (%g, %g); want (0.5, 0.5) per plan 08.5-10", c.Metadata.TverskyAlpha, c.Metadata.TverskyBeta)
	}
	tverskyAlpha := c.Metadata.TverskyAlpha
	tverskyBeta := c.Metadata.TverskyBeta

	for _, e := range c.Entries {
		e := e // local copy for the closure

		// q=2 sub-tests — every entry has q=2 scores.
		runQGramAssertions(t, &c, e, 2, e.Q2, tverskyAlpha, tverskyBeta)

		// q=3 sub-tests — entries with skip_q3=true emit q3:null in the
		// JSON and are skipped here.
		if e.Q3 != nil {
			runQGramAssertions(t, &c, e, 3, *e.Q3, tverskyAlpha, tverskyBeta)
		}
	}
}

// runQGramAssertions runs the four per-surface assertions at a given q.
// Factored to avoid duplicating the q=2 and q=3 loops.
func runQGramAssertions(t *testing.T, c *qgramCorpus, e qgramEntry, q int, scores qgramQ2Scores, alpha, beta float64) {
	t.Helper()

	t.Run(e.Name+"/q"+strconv.Itoa(q)+"/qgram_jaccard", func(t *testing.T) {
		got := fuzzymatch.QGramJaccardScore(e.A, e.B, q)
		delta := math.Abs(got - scores.QGramJaccard)
		if delta > qgramCrossValidationEpsilonStandard {
			t.Errorf("QGramJaccardScore(%q, %q, %d) = %.17g; py_stringmatching Jaccard = %.17g (delta %.2e, tol %g, pysm %s, python %s)",
				e.A, e.B, q, got, scores.QGramJaccard, delta, qgramCrossValidationEpsilonStandard,
				c.Metadata.PyStringMatchingVersion, c.Metadata.PythonVersion)
		}
	})

	t.Run(e.Name+"/q"+strconv.Itoa(q)+"/sorensen_dice", func(t *testing.T) {
		got := fuzzymatch.SorensenDiceScore(e.A, e.B, q)
		delta := math.Abs(got - scores.SorensenDice)
		if delta > qgramCrossValidationEpsilonStandard {
			t.Errorf("SorensenDiceScore(%q, %q, %d) = %.17g; py_stringmatching Dice = %.17g (delta %.2e, tol %g, pysm %s, python %s)",
				e.A, e.B, q, got, scores.SorensenDice, delta, qgramCrossValidationEpsilonStandard,
				c.Metadata.PyStringMatchingVersion, c.Metadata.PythonVersion)
		}
	})

	t.Run(e.Name+"/q"+strconv.Itoa(q)+"/cosine", func(t *testing.T) {
		got := fuzzymatch.CosineScore(e.A, e.B, q)
		delta := math.Abs(got - scores.Cosine)
		if delta > qgramCrossValidationEpsilonCosine {
			t.Errorf("CosineScore(%q, %q, %d) = %.17g; py_stringmatching Cosine = %.17g (delta %.2e, tol %g, pysm %s, python %s)",
				e.A, e.B, q, got, scores.Cosine, delta, qgramCrossValidationEpsilonCosine,
				c.Metadata.PyStringMatchingVersion, c.Metadata.PythonVersion)
		}
	})

	t.Run(e.Name+"/q"+strconv.Itoa(q)+"/tversky", func(t *testing.T) {
		got := fuzzymatch.TverskyScore(e.A, e.B, q, alpha, beta)
		delta := math.Abs(got - scores.Tversky)
		if delta > qgramCrossValidationEpsilonStandard {
			t.Errorf("TverskyScore(%q, %q, %d, %g, %g) = %.17g; py_stringmatching Tversky = %.17g (delta %.2e, tol %g, pysm %s, python %s)",
				e.A, e.B, q, alpha, beta, got, scores.Tversky, delta, qgramCrossValidationEpsilonStandard,
				c.Metadata.PyStringMatchingVersion, c.Metadata.PythonVersion)
		}
	})
}

// TestQGram_CrossValidation_CorpusShape asserts the committed corpus
// contains at least 30 entries spanning the categories promised by plan
// 08.5-10 task 2:
//
//   - identity / both-empty / one-empty (≥ 3 — checked via "identity",
//     "both_empty", "one_empty")
//   - mismatched-length pairs (≥ 1 — checked via "kitten_sitting",
//     "saturday_sunday", "jellyfish_smellyfish")
//   - disjoint pairs (≥ 1 — checked via "fully_different" prefix)
//   - subset pairs (≥ 1 — checked via "subset_" prefix)
//   - short-input edge cases (≥ 1 — checked via "shorter_than_" prefix)
//   - ratio stressors (≥ 1 — checked via "ratio_stressor_" prefix)
//
// Together with TestQGram_CrossValidation, this shape gate prevents a
// future regression where someone trims the corpus to remove a
// load-bearing fixture (which would silently disarm the relevant gate
// without surfacing a delta).
func TestQGram_CrossValidation_CorpusShape(t *testing.T) {
	path := filepath.Join("testdata", "cross-validation", "qgram", "vectors.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	var c qgramCorpus
	if err := json.Unmarshal(raw, &c); err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}

	if len(c.Entries) < 30 {
		t.Errorf("corpus has %d entries; want >= 30 (plan 08.5-10 task 2 success criterion)", len(c.Entries))
	}

	if c.Metadata.PyStringMatchingVersion != "0.4.7" {
		t.Errorf("corpus _metadata.py_stringmatching_version = %q; want %q (the pinned version per plan 08.5-10)", c.Metadata.PyStringMatchingVersion, "0.4.7")
	}

	categories := map[string]bool{
		"identity":        false,
		"both_empty":      false,
		"one_empty":       false,
		"kitten_sitting":  false,
		"fully_different": false,
		"subset_":         false,
		"shorter_than_":   false,
		"ratio_stressor_": false,
		"single_qgram_":   false,
	}
	for _, e := range c.Entries {
		for cat := range categories {
			if strings.Contains(e.Name, cat) {
				categories[cat] = true
			}
		}
	}
	for cat, found := range categories {
		if !found {
			t.Errorf("corpus is missing the %q category (no entry name contains the substring) — was a load-bearing fixture trimmed?", cat)
		}
	}
}
