// Copyright 2026 AxonOps Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// token_ratio_cross_validation_test.go asserts agreement between the
// project's token-tier Indel-based ratios and the RapidFuzz 3.14.5
// reference corpus committed at
// testdata/cross-validation/token-ratios/vectors.json. The corpus
// carries four scores per entry — token_sort_ratio, token_set_ratio,
// partial_ratio_bytes, partial_ratio_runes — emitted by
// scripts/gen-token-ratio-cross-validation.py with the rapidfuzz
// version pinned to RAPIDFUZZ_VERSION = "3.14.5".
//
// Tolerance: |our_score - rapidfuzz_score| <= 1e-9 per entry per surface
// (matches the Phase 3 SWG and Phase 4 Ratcliff-Obershelp epsilon
// conventions).
//
// Wave-1 surface (this plan, 06-01):
//   - token_sort sub-tests ASSERT — every entry's score is compared
//     against RapidFuzz token_sort_ratio.
//   - token_set / partial_bytes / partial_runes sub-tests SKIP with
//     an explicit "plan 06-NN will land …" message until those plans
//     land. Plans 06-02 (TokenSetRatio) and 06-03 (PartialRatio)
//     REMOVE the t.Skip and add the assertion bodies.
//
// The corpus is regenerated by `make regen-token-ratio-cross-validation`
// (developer-only — requires `pip install rapidfuzz==3.14.5`). CI does
// NOT require Python at test time; the committed JSON is the
// verification fixture read directly by Go.
//
// Failure messages include the rapidfuzz_version, python_version, and
// the surface field name for triage — same pattern as
// ratcliff_obershelp_test.go::TestRatcliffObershelp_CrossValidation.

package fuzzymatch_test

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/axonops/fuzzymatch"
)

// tokenRatioCrossValidationEpsilon is the float-comparison tolerance for
// per-entry cross-validation assertions. Same convention as the
// Phase 3 SWG and Phase 4 Ratcliff-Obershelp corpora.
const tokenRatioCrossValidationEpsilon = 1e-9

// tokenRatioEntry is one entry in the committed
// testdata/cross-validation/token-ratios/vectors.json corpus produced by
// scripts/gen-token-ratio-cross-validation.py. The four scoring fields
// use pointer-to-float64 so the loader can distinguish JSON null
// (partial_only entries' token_sort / token_set fields) from the
// legitimate 0.0 score.
type tokenRatioEntry struct {
	Name              string   `json:"name"`
	A                 string   `json:"a"`
	B                 string   `json:"b"`
	TokenSortRatio    *float64 `json:"token_sort_ratio"`
	TokenSetRatio     *float64 `json:"token_set_ratio"`
	PartialRatioBytes *float64 `json:"partial_ratio_bytes"`
	PartialRatioRunes *float64 `json:"partial_ratio_runes"`
	PartialOnly       bool     `json:"partial_only,omitempty"`
}

// tokenRatioMetadata is the top-level _metadata block — pins the
// generator's pinned rapidfuzz version, the Python version that
// produced the corpus, and the regeneration timestamp (informational
// only — the test does not assert byte-stability on the timestamp).
type tokenRatioMetadata struct {
	RapidFuzzVersion string `json:"rapidfuzz_version"`
	PythonVersion    string `json:"python_version"`
	RegeneratedAt    string `json:"regenerated_at"`
}

// tokenRatioCorpus is the top-level shape of the corpus JSON file —
// see scripts/gen-token-ratio-cross-validation.py for the generator
// schema.
type tokenRatioCorpus struct {
	Version  int                `json:"version"`
	Metadata tokenRatioMetadata `json:"_metadata"`
	Entries  []tokenRatioEntry  `json:"entries"`
}

// TestTokenRatios_CrossValidation asserts agreement between the
// project's TokenSortRatioScore (Wave 1 — this plan) and RapidFuzz
// 3.14.5's token_sort_ratio. Plans 06-02 / 06-03 extend the
// per-surface sub-test loop to assert TokenSetRatio / PartialRatio
// surfaces as those algorithms land. The structurally-complete loader
// is set up now so later plans only need to remove t.Skip lines and
// add the score-call.
func TestTokenRatios_CrossValidation(t *testing.T) {
	path := filepath.Join("testdata", "cross-validation", "token-ratios", "vectors.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("TestTokenRatios_CrossValidation: read %s: %v (regenerate with `make regen-token-ratio-cross-validation`)", path, err)
	}
	var c tokenRatioCorpus
	if err := json.Unmarshal(raw, &c); err != nil {
		t.Fatalf("TestTokenRatios_CrossValidation: parse %s: %v", path, err)
	}
	if c.Version != 1 {
		t.Fatalf("TestTokenRatios_CrossValidation: unsupported corpus version %d (want 1)", c.Version)
	}
	if len(c.Entries) == 0 {
		t.Fatalf("TestTokenRatios_CrossValidation: empty corpus")
	}
	// Pin the rapidfuzz_version metadata field — corpus tampering (or
	// regeneration with a non-pinned rapidfuzz release) surfaces here
	// rather than via misleading per-entry deltas.
	if c.Metadata.RapidFuzzVersion == "" {
		t.Fatalf("TestTokenRatios_CrossValidation: corpus missing _metadata.rapidfuzz_version — regenerate with `make regen-token-ratio-cross-validation`")
	}
	if c.Metadata.PythonVersion == "" {
		t.Fatalf("TestTokenRatios_CrossValidation: corpus missing _metadata.python_version — regenerate with `make regen-token-ratio-cross-validation`")
	}
	// Parse the python_version into (major, minor) and assert >= 3.7,
	// mirroring the script-side _check_python_version gate. Without
	// this gate (review WR-04-equivalent), a corpus regenerated on
	// Python < 3.7 with missing field could silently drift while the
	// per-entry comparison stays green.
	parts := strings.SplitN(c.Metadata.PythonVersion, ".", 3)
	if len(parts) < 2 {
		t.Fatalf("TestTokenRatios_CrossValidation: malformed python_version %q (want major.minor[.patch])", c.Metadata.PythonVersion)
	}
	major, err1 := strconv.Atoi(parts[0])
	minor, err2 := strconv.Atoi(parts[1])
	if err1 != nil || err2 != nil {
		t.Fatalf("TestTokenRatios_CrossValidation: non-numeric python_version %q", c.Metadata.PythonVersion)
	}
	if major < 3 || (major == 3 && minor < 7) {
		t.Fatalf("TestTokenRatios_CrossValidation: corpus generated with Python %s; script minimum is 3.7 (required for dict insertion-order stability)", c.Metadata.PythonVersion)
	}

	for _, e := range c.Entries {
		e := e // local copy for the closure

		// TokenSortRatio sub-test — Wave 1 ASSERTS.
		t.Run(e.Name+"/token_sort", func(t *testing.T) {
			if e.TokenSortRatio == nil {
				t.Skip("partial_only entry — token_sort_ratio not computed by the generator")
			}
			got := fuzzymatch.TokenSortRatioScore(e.A, e.B)
			delta := math.Abs(got - *e.TokenSortRatio)
			if delta > tokenRatioCrossValidationEpsilon {
				t.Errorf("TokenSortRatioScore(%q, %q) = %.17g; rapidfuzz token_sort_ratio = %.17g (delta %.2e, tol %g, rapidfuzz %s, python %s)",
					e.A, e.B, got, *e.TokenSortRatio, delta, tokenRatioCrossValidationEpsilon,
					c.Metadata.RapidFuzzVersion, c.Metadata.PythonVersion)
			}
		})

		// TokenSetRatio sub-test — Wave 1 SKIPS pending plan 06-02.
		t.Run(e.Name+"/token_set", func(t *testing.T) {
			t.Skip("plan 06-02 will land TokenSetRatioScore — see VALIDATION.md row 06-02-01; remove this t.Skip and add the assertion against e.TokenSetRatio")
		})

		// PartialRatio bytes sub-test — Wave 1 SKIPS pending plan 06-03.
		t.Run(e.Name+"/partial_bytes", func(t *testing.T) {
			t.Skip("plan 06-03 will land PartialRatioScore — see VALIDATION.md row 06-03-01; remove this t.Skip and add the assertion against e.PartialRatioBytes")
		})

		// PartialRatio runes sub-test — Wave 1 SKIPS pending plan 06-03.
		t.Run(e.Name+"/partial_runes", func(t *testing.T) {
			t.Skip("plan 06-03 will land PartialRatioScoreRunes — see VALIDATION.md row 06-03-02; remove this t.Skip and add the assertion against e.PartialRatioRunes")
		})
	}
}

// TestTokenRatios_CrossValidation_CorpusShape asserts the committed
// corpus contains at least 20 entries spanning all the categories
// promised by 06-01 task 3:
//
//   - identity / both-empty / one-empty (3 entries)
//   - token-reordered (≥ 1 — checked via "reorder" substring)
//   - subset (≥ 1 — checked via "subset" substring)
//   - tokenset edge (≥ 1 — checked via "tokenset" substring)
//   - partial Pitfall-3 fixture (≥ 1 — checked via "partial_" substring)
//   - ASCII medium / long (≥ 1 — checked via "ascii" substring)
//
// Together with TestTokenRatios_CrossValidation, this shape gate
// prevents a future regression where someone trims the corpus to
// remove a load-bearing fixture (which would silently disarm the
// relevant keystone gate without surfacing a delta).
func TestTokenRatios_CrossValidation_CorpusShape(t *testing.T) {
	path := filepath.Join("testdata", "cross-validation", "token-ratios", "vectors.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	var c tokenRatioCorpus
	if err := json.Unmarshal(raw, &c); err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}

	if len(c.Entries) < 20 {
		t.Errorf("corpus has %d entries; want >= 20 (06-01 task 3 success criterion)", len(c.Entries))
	}

	if c.Metadata.RapidFuzzVersion != "3.14.5" {
		t.Errorf("corpus _metadata.rapidfuzz_version = %q; want %q (the pinned version per CONTEXT.md §1 LOCKED)", c.Metadata.RapidFuzzVersion, "3.14.5")
	}

	// Substring-membership check for each required category.
	categories := map[string]bool{
		"identity":    false,
		"empty":       false,
		"reorder":     false,
		"subset":      false,
		"tokenset":    false,
		"partial_":    false,
		"ascii":       false,
		"disjoint":    false,
		"low_overlap": false,
	}
	for _, e := range c.Entries {
		for cat := range categories {
			if strings.Contains(e.Name, cat) {
				categories[cat] = true
			}
		}
	}
	for cat, found := range categories {
		if !found {
			t.Errorf("corpus is missing the %q category (no entry name contains the substring) — was a load-bearing fixture trimmed?", cat)
		}
	}
}
